import csv
from sqlalchemy.orm import Session
from .interfaces import IClinicRepository
from dal.models import Patient, Appointment, Dentist


class ClinicRepository(IClinicRepository):
    def __init__(self, db_session: Session):
        # Save the database session
        self.session = db_session

    def read_csv(self, file_path: str) -> list:
        """Reads data from CSV for initial database population"""
        data = []
        with open(file_path, mode="r", encoding="utf-8") as file:
            reader = csv.DictReader(file)
            for row in reader:
                data.append(row)
        return data

    def save_models(self, models_list: list):
        """Saves a list of objects to the database"""
        self.session.add_all(models_list)
        self.session.commit()

    # --- READ METHODS ---

    def get_all_patients(self):
        """Returns a list of all patients"""
        return self.session.query(Patient).all()

    def get_all_appointments(self):
        """Returns all records from the appointments log"""
        return self.session.query(Appointment).all()

    def get_all_dentists(self):
        """Returns a list of all dentists (for dropdown lists)"""
        return self.session.query(Dentist).all()

    def get_patient_by_id(self, patient_id: int):
        """Finds a patient by ID (needed for the edit form)"""
        return self.session.query(Patient).filter(Patient.id == patient_id).first()

    def get_patient_by_email(self, email: str):
        """Quick search for a patient by email (for uniqueness check)"""
        return self.session.query(Patient).filter(Patient.email == email).first()

    def get_patient_by_card_id(self, card_id: int):
        """Quick search by card ID (for uniqueness check)"""
        return (
            self.session.query(Patient).filter(Patient.patientCardID == card_id).first()
        )

    # --- CREATE METHODS ---

    def add_patient(self, patient: Patient):
        """Adds a new patient to the database"""
        self.session.add(patient)
        self.session.commit()
        self.session.refresh(patient)  # Retrieve the ID generated by the database
        return patient

    def add_appointment(self, appointment: Appointment):
        """Creates a new appointment record in the log"""
        self.session.add(appointment)
        self.session.commit()

    # --- UPDATE METHOD ---

    def update_patient(
        self, patient_id: int, name: str, email: str, card_id: int, history: str
    ):
        """Updates data for an existing patient"""
        patient = self.get_patient_by_id(patient_id)
        if patient:
            patient.name = name
            patient.email = email
            patient.patientCardID = card_id
            patient.medicalHistory = history
            self.session.commit()

    # --- DELETE METHOD ---

    def delete_appointment(self, appt_id: int):
        """
        Deletes a SPECIFIC appointment record.
        The patient remains in the database, but this specific row is removed.
        """
        appt = self.session.query(Appointment).filter(Appointment.id == appt_id).first()
        if appt:
            self.session.delete(appt)
            self.session.commit()
